# Generated by Django 4.1.3 on 2023-04-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_exp', models.CharField(max_length=200)),
                ('exp', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_skill', models.CharField(max_length=200)),
                ('skill', models.CharField(max_length=600)),
            ],
        ),
    ]
