# Generated by Django 4.1.3 on 2023-04-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=200)),
                ('rating_val', models.IntegerField()),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
    ]
